weights: /content/drive/MyDrive/GCN-HAR/work_dir_tam/epoch55_model.pt

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 60
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
    
# training
device: [0]